# https://taskfile.dev

version: "3"

tasks:
  prepare:
    cmds:
      - npx -y mustache config/{{.ENV}}.json substreams.template.yaml > substreams.yaml

  prepare:dev:
    cmds:
      - task: prepare
        vars:
          ENV: dev

  proto:
    cmds:
      - substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google"

  build:
    cmds:
      - cargo build --release --target wasm32-unknown-unknown

  pack:
    cmds:
      - substreams pack ./substreams.yaml

  roll:dev:
    cmds:
      - task: prepare:dev
      - task: proto
      - task: build
      - task: pack
  
  run:
    internal: true
    cmds:
      - task: proto
      - task: build 
      - substreams run -e {{.FIREHOSE_URL}} ./substreams.yaml map_events --start-block {{.START_BLOCK}} --stop-block {{.STOP_BLOCK}} -p map_registry="registry={{.REGISTRY_ADDRESS}}" -p map_events="registry_address={{.REGISTRY_ADDRESS}}&chain_id={{.CHAIN_ID}}"

  run:dev:
    internal: true
    cmds:
      - task: run
        vars:
          START_BLOCK: 42987350
          STOP_BLOCK: 42987375
          FIREHOSE_URL: mumbai.streamingfast.io:443
          REGISTRY_ADDRESS: 0x8d764bea078d78a671c9efda3b2a7484f4376e02
          CHAIN_ID: 80001
