# https://taskfile.dev

version: "3"

tasks:
  proto:
    cmds:
      - substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google"

  build:
    cmds:
      - cargo build --release --target wasm32-unknown-unknown

  pack:
    cmds:
      - substreams pack ./substreams.yaml

  roll:
    cmds:
      - task: proto
      - task: build
      - task: pack

  run:
    internal: true
    cmds:
      - task: proto
      - task: build
      - substreams run -e {{.FIREHOSE_URL}} ./substreams.yaml map_events --start-block {{.START_BLOCK}} --stop-block {{.STOP_BLOCK}} --network {{.NETWORK}}

  run:dev:
    cmds:
      - task: run
        vars:
          START_BLOCK: 5719440
          STOP_BLOCK: 5719450
          FIREHOSE_URL: sepolia.eth.streamingfast.io:443
          NETWORK: dev

  # TODO: Use staging values here. Right now just fake dev values
  run:stg:
    cmds:
      - task: run
        vars:
          START_BLOCK: 52675760
          STOP_BLOCK: 52676135
          FIREHOSE_URL: polygon.streamingfast.io:443
          NETWORK: stg
