// DO NOT EDIT - the file is generated by build script
#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "./SafeFactory.rs"]
pub mod SafeFactory;

#[rustfmt::skip]
#[allow(unused_imports)]
#[path = "./SafeL2.rs"]
pub mod SafeL2;
